language: java

jdk:
  - oraclejdk8

script: mvn --settings .travis/settings.xml clean  verify

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: idealo/test-logger
      tags: true
      jdk: oraclejdk8


notifications:
  email:
    - lars.gohlke+github_test-logger@idealo.de